ALTER TYPE "AgentTaskStatus" ADD VALUE IF NOT EXISTS 'PARTIAL' AFTER 'SUCCEEDED';

ALTER TABLE "AgentRun"
  ADD COLUMN "maxToolCalls" INTEGER NOT NULL DEFAULT 16,
  ADD COLUMN "maxSearchQueries" INTEGER NOT NULL DEFAULT 8,
  ADD COLUMN "maxCreditCost" INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN "timeoutSeconds" INTEGER NOT NULL DEFAULT 900,
  ADD COLUMN "toolCallCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "searchQueryCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "creditCost" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "deadlineAt" TIMESTAMP(3);
