-- Capability presets are insert-only. Existing rows and administrator edits are
-- deliberately left untouched; the same IDs/keys also make restoration idempotent.
INSERT INTO "Assistant" ("id", "name", "description", "systemPrompt", "defaultModel", "templateIds", "enabled", "visibility", "sortOrder", "createdAt", "updatedAt") VALUES
  ('xinyue_assistant_general', '通用工作助手', '处理日常问答、总结、改写、翻译和方案梳理，适合作为默认助手。', '你是可靠的通用工作助手。先识别用户真正要完成的任务，再给出准确、清晰、可直接使用的结果。区分事实、推断和建议；信息不足时明确说明，不编造来源、数字或承诺。优先使用简洁标题、清单和表格组织复杂内容。', '', '["prompt-rewrite","prompt-structured-summary","prompt-accurate-translation"]'::jsonb, true, 'PUBLIC', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xinyue_assistant_research', '深度调研助手', '用于联网调研、竞品对比、资料核验和决策备忘录。', '你是严谨的研究分析助手。先拆解研究问题和证据标准，再检索或整理多个独立来源。明确区分已证实事实、合理推断和未知信息；来源冲突时并列说明，不得编造引用。结论前置，并给出关键证据、风险、限制和下一步。', '', '["prompt-option-comparison","prompt-decision-memo","prompt-paper-reading"]'::jsonb, true, 'PUBLIC', 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xinyue_assistant_office', '办公写作助手', '起草邮件、周报、项目计划、会议材料和正式文档。', '你是专业办公写作助手。先确认受众、目的、语气和交付格式，再输出可直接使用的完整成稿。保留用户提供的事实和术语，不用空泛套话补齐未知信息。涉及行动项时明确负责人、时间、依赖和验收标准。', '', '["prompt-business-email","prompt-weekly-report","prompt-project-plan"]'::jsonb, true, 'PUBLIC', 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xinyue_assistant_data', '数据分析助手', '解释表格和经营数据，梳理指标、异常、口径与行动建议。', '你是数据分析助手。分析前先核对字段、单位、时间范围、缺失值和计算口径；展示关键计算过程，区分相关性与因果关系。优先用表格呈现指标、异常和对比，所有结论必须能追溯到输入数据。没有数据时只提供分析框架，不虚构数值。', '', '["prompt-data-insights","prompt-option-comparison","prompt-risk-review"]'::jsonb, true, 'PUBLIC', 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xinyue_assistant_code', '代码与架构助手', '用于代码审查、故障诊断、测试设计和技术方案。', '你是高级软件工程师。优先保证正确性、安全性、可维护性和可验证性。审查时先列可复现问题并按严重程度排序；实现时给出完整代码、边界处理和验证方式。尊重现有项目约束，不把个人风格偏好当作缺陷。', '', '["prompt-code-review","prompt-debug-assistant","prompt-test-cases","prompt-api-design"]'::jsonb, true, 'PUBLIC', 70, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xinyue_assistant_meeting', '会议纪要助手', '从会议文字或转写内容提炼决定、待办、负责人和风险。', '你是会议纪要助手。严格依据原始内容整理议题、关键讨论、已确认决定、待确认事项和行动项。不得猜测未明确出现的负责人、截止日期或结论；缺失项标记为待确认。输出摘要、决定、行动项表格、风险和后续议题。', '', '["prompt-meeting-summary","prompt-structured-summary"]'::jsonb, true, 'PUBLIC', 80, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ToolDefinition" ("id", "key", "name", "description", "icon", "kind", "authType", "documentationUrl", "credentialFields", "endpoint", "httpMethod", "timeoutMs", "headers", "inputSchema", "scopes", "enabled", "requiresApproval", "createdAt", "updatedAt") VALUES
  ('xinyue_tool_project_context', 'project_context', '项目上下文', '平台内置：读取当前项目目标、说明、工作流状态、版本和文件摘要，无需第三方服务。', 'folder-kanban', 'BUILT_IN', 'NONE', '', '[]'::jsonb, '', 'POST', 15000, '{}'::jsonb, '{"type":"object","properties":{},"additionalProperties":false}'::jsonb, '["project:read"]'::jsonb, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xinyue_tool_file_catalog', 'file_catalog', '文件目录', '平台内置：按名称、类型或项目检索用户已授权文件，无需第三方服务。', 'files', 'BUILT_IN', 'NONE', '', '[]'::jsonb, '', 'POST', 15000, '{}'::jsonb, '{"type":"object","properties":{"query":{"type":"string","maxLength":300},"kind":{"type":"string","enum":["IMAGE","VIDEO","FILE"]},"projectId":{"type":"string","maxLength":100}},"additionalProperties":false}'::jsonb, '["asset:read"]'::jsonb, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xinyue_tool_data_summary', 'data_summary', '数据汇总', '平台内置：对数字或表格行计算计数、合计、均值、中位数、最小值和最大值。', 'table-2', 'BUILT_IN', 'NONE', '', '[]'::jsonb, '', 'POST', 15000, '{}'::jsonb, '{"type":"object","properties":{"values":{"type":"array","maxItems":20000,"items":{"type":["number","string"]}},"rows":{"type":"array","maxItems":5000,"items":{"type":"object"}}},"anyOf":[{"required":["values"]},{"required":["rows"]}],"additionalProperties":false}'::jsonb, '["data:read"]'::jsonb, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xinyue_tool_current_time', 'current_time', '日期与时间', '平台内置：返回服务器当前时间和时区，无需第三方服务。', 'clock-3', 'BUILT_IN', 'NONE', '', '[]'::jsonb, '', 'POST', 5000, '{}'::jsonb, '{"type":"object","properties":{},"additionalProperties":false}'::jsonb, '["system:time"]'::jsonb, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xinyue_tool_n8n', 'n8n_workflow', 'n8n 工作流（需部署）', '接入自托管或云端 n8n Webhook。先完成 n8n 部署并创建生产 Webhook，再填写 Endpoint；如启用鉴权，请在敏感请求头中配置。', 'workflow', 'BUILT_IN', 'NONE', 'https://docs.n8n.io/hosting/installation/docker/', '[]'::jsonb, '', 'POST', 60000, '{}'::jsonb, '{"type":"object","properties":{"task":{"type":"string","description":"要交给工作流处理的任务"},"data":{"type":"object","description":"结构化业务数据"}},"required":["task"],"additionalProperties":true}'::jsonb, '["workflow:execute"]'::jsonb, false, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xinyue_tool_dify', 'dify_workflow', 'Dify 工作流（需部署/配置）', '调用 Dify Workflow API。填写 /v1/workflows/run 地址，并在敏感请求头配置 Authorization: Bearer app-xxx 后再启用。', 'workflow', 'BUILT_IN', 'NONE', 'https://docs.dify.ai/en/getting-started/install-self-hosted/docker-compose', '[]'::jsonb, '', 'POST', 90000, '{}'::jsonb, '{"type":"object","properties":{"inputs":{"type":"object"},"response_mode":{"type":"string","enum":["blocking"],"default":"blocking"},"user":{"type":"string"}},"required":["inputs"],"additionalProperties":true}'::jsonb, '["workflow:execute"]'::jsonb, false, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xinyue_tool_fastgpt', 'fastgpt_workflow', 'FastGPT 应用（需部署/配置）', '调用 FastGPT 应用 API。完成部署并创建应用后，填写 API 地址并在敏感请求头配置 Bearer Key，检测成功后再启用。', 'bot', 'BUILT_IN', 'NONE', 'https://doc.fastgpt.io/docs/development/docker/', '[]'::jsonb, '', 'POST', 90000, '{}'::jsonb, '{"type":"object","properties":{"chatId":{"type":"string"},"stream":{"type":"boolean","default":false},"detail":{"type":"boolean","default":true},"messages":{"type":"array","items":{"type":"object"}}},"required":["messages"],"additionalProperties":true}'::jsonb, '["workflow:execute"]'::jsonb, false, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO NOTHING;
