INSERT INTO "PromptTemplate" ("id", "title", "description", "prompt", "category", "variables", "enabled", "sortOrder", "updatedAt")
VALUES
  ('prompt-rewrite', '润色与改写', '保持原意，改善表达、结构和可读性。', E'请将下面的内容进行专业润色：\n\n{{content}}\n\n要求：保持原意，优化结构和措辞，并输出可直接使用的版本。', '写作', '["content"]'::jsonb, true, 10, CURRENT_TIMESTAMP),
  ('prompt-structured-summary', '结构化总结', '从长内容中提取结论、依据和行动项。', E'请总结以下内容：\n\n{{content}}\n\n按“核心结论、关键依据、重要数据、行动项、待确认问题”组织。不要补充原文没有的信息。', '写作', '["content"]'::jsonb, true, 20, CURRENT_TIMESTAMP),
  ('prompt-continue-writing', '续写与补全', '沿用原文语气和逻辑自然续写。', E'请续写以下内容：\n\n{{content}}\n\n续写方向：{{direction}}\n\n保持人物、事实、视角和语言风格一致，避免重复前文。', '写作', '["content","direction"]'::jsonb, true, 30, CURRENT_TIMESTAMP),
  ('prompt-accurate-translation', '专业翻译', '按目标语言和使用场景完成自然翻译。', E'将以下内容翻译为{{language}}：\n\n{{content}}\n\n使用场景：{{scenario}}。保留专有名词、数字和格式，表达自然，不逐字硬译。', '写作', '["content","language","scenario"]'::jsonb, true, 40, CURRENT_TIMESTAMP),
  ('prompt-meeting-summary', '会议纪要', '将零散记录整理成行动项明确的会议纪要。', E'请将下面的会议记录整理为结构化纪要：\n\n{{notes}}\n\n请包含：结论、待办事项、负责人、截止时间和未决问题；不确定的信息请明确标注。', '办公', '["notes"]'::jsonb, true, 110, CURRENT_TIMESTAMP),
  ('prompt-business-email', '商务邮件', '生成清晰、礼貌且有明确下一步的邮件。', E'请起草一封商务邮件。\n收件人：{{recipient}}\n目的：{{goal}}\n背景：{{context}}\n\n要求主题明确、正文简洁、语气专业，并给出清晰的下一步。', '办公', '["recipient","goal","context"]'::jsonb, true, 120, CURRENT_TIMESTAMP),
  ('prompt-weekly-report', '周报整理', '把工作记录整理为结果导向的周报。', E'根据以下工作记录生成周报：\n\n{{notes}}\n\n按“本周成果、关键数据、问题与风险、下周计划、需要协助”输出，突出结果而非流水账。', '办公', '["notes"]'::jsonb, true, 130, CURRENT_TIMESTAMP),
  ('prompt-project-plan', '项目执行计划', '把目标拆成里程碑、任务、风险和验收标准。', E'为以下项目制定执行计划：\n目标：{{goal}}\n期限：{{deadline}}\n可用资源：{{resources}}\n\n请包含范围、里程碑、任务分工、依赖、风险、验收标准和复盘节点。', '办公', '["goal","deadline","resources"]'::jsonb, true, 140, CURRENT_TIMESTAMP),
  ('prompt-product-copy', '商品卖点提炼', '从商品信息中提炼清晰、可信、可转化的卖点。', E'请根据以下商品信息提炼商品卖点：\n\n{{product}}\n\n请输出：核心卖点、目标人群、使用场景、注意事项。避免夸大和无法验证的承诺。', '营销', '["product"]'::jsonb, true, 210, CURRENT_TIMESTAMP),
  ('prompt-ad-variants', '广告文案变体', '针对不同诉求生成可测试的广告版本。', '为{{product}}面向{{audience}}生成 5 组适用于{{platform}}的广告文案。每组包含标题、正文、行动号召和主打角度，并说明适合测试的变量。', '营销', '["product","audience","platform"]'::jsonb, true, 220, CURRENT_TIMESTAMP),
  ('prompt-audience-persona', '用户画像', '根据已有信息形成可执行的目标用户画像。', E'为以下业务建立目标用户画像：\n业务：{{business}}\n已有证据：{{evidence}}\n\n输出用户目标、痛点、触发场景、决策阻力、信息渠道和转化建议，并区分事实与假设。', '营销', '["business","evidence"]'::jsonb, true, 230, CURRENT_TIMESTAMP),
  ('prompt-campaign-plan', '营销活动方案', '从目标到渠道、节奏和指标规划完整活动。', E'设计一套营销活动。\n目标：{{goal}}\n受众：{{audience}}\n预算：{{budget}}\n\n请给出核心策略、渠道组合、内容主题、时间节奏、转化路径、指标和风险预案。', '营销', '["goal","audience","budget"]'::jsonb, true, 240, CURRENT_TIMESTAMP),
  ('prompt-code-review', '代码审查', '按风险优先级检查代码中的问题并给出修复建议。', E'请审查下面的代码：\n\n{{code}}\n\n请优先指出会导致错误、数据丢失、安全风险或兼容性问题的地方，并给出最小可行修复建议。', '编程', '["code"]'::jsonb, true, 310, CURRENT_TIMESTAMP),
  ('prompt-debug-assistant', '错误诊断', '结合报错和上下文定位根因并给出验证步骤。', E'请诊断以下问题。\n报错：{{error}}\n运行环境与复现步骤：{{context}}\n相关代码：\n{{code}}\n\n请给出最可能根因、排查顺序、修复方案和回归验证项。', '编程', '["error","context","code"]'::jsonb, true, 320, CURRENT_TIMESTAMP),
  ('prompt-test-cases', '测试用例设计', '根据需求生成正常、边界和异常测试。', E'为以下需求设计测试用例：\n{{requirement}}\n技术栈：{{stack}}\n\n覆盖正常路径、边界条件、权限、安全、并发和失败恢复；给出测试数据、步骤和预期结果。', '编程', '["requirement","stack"]'::jsonb, true, 330, CURRENT_TIMESTAMP),
  ('prompt-api-design', 'API 设计', '设计可演进、可验证的接口契约。', E'为以下功能设计 API：\n功能：{{feature}}\n约束：{{constraints}}\n\n请给出端点、方法、鉴权、请求响应结构、错误码、幂等、分页和版本兼容策略。', '编程', '["feature","constraints"]'::jsonb, true, 340, CURRENT_TIMESTAMP),
  ('prompt-concept-tutor', '概念讲解', '按学习者水平分层解释复杂概念。', '请向{{level}}水平的学习者讲解“{{topic}}”。先给直观解释，再给准确定义、例子、常见误区和一个自测问题。', '学习', '["topic","level"]'::jsonb, true, 410, CURRENT_TIMESTAMP),
  ('prompt-learning-plan', '学习计划', '根据目标和可用时间安排阶段化学习路径。', E'制定学习计划。\n目标：{{goal}}\n周期：{{duration}}\n当前基础：{{baseline}}\n\n按周给出主题、练习、输出物、检查点和调整标准。', '学习', '["goal","duration","baseline"]'::jsonb, true, 420, CURRENT_TIMESTAMP),
  ('prompt-quiz-generator', '练习题生成', '生成由浅入深并附解析的练习题。', '围绕“{{topic}}”生成 10 道{{difficulty}}练习题，包含选择、简答和应用题。先列题目，最后单独给答案、解析和考查点。', '学习', '["topic","difficulty"]'::jsonb, true, 430, CURRENT_TIMESTAMP),
  ('prompt-paper-reading', '论文阅读助手', '提取研究问题、方法、证据和局限。', E'阅读以下论文内容：\n\n{{paper}}\n\n提取研究问题、核心方法、数据与实验、主要结论、创新点、局限和可复现性风险；不要把作者观点当作已证实事实。', '学习', '["paper"]'::jsonb, true, 440, CURRENT_TIMESTAMP),
  ('prompt-option-comparison', '方案对比', '按统一维度比较多个候选方案。', E'比较以下方案：{{options}}\n评估标准：{{criteria}}\n\n使用统一维度列出优势、缺点、成本、风险和适用条件，最后给出有条件的建议，不要假装存在唯一答案。', '分析', '["options","criteria"]'::jsonb, true, 510, CURRENT_TIMESTAMP),
  ('prompt-data-insights', '数据洞察', '从数据中识别趋势、异常和可验证假设。', E'分析以下数据：\n{{data}}\n分析目标：{{goal}}\n\n指出趋势、分布、异常、可能解释和数据限制，并给出下一步需要验证的假设。相关性不要表述为因果。', '分析', '["data","goal"]'::jsonb, true, 520, CURRENT_TIMESTAMP),
  ('prompt-decision-memo', '决策备忘录', '把复杂选择整理为可审议的决策材料。', E'为以下决策撰写备忘录：\n决策事项：{{decision}}\n已知事实：{{facts}}\n\n包含背景、目标、选项、权衡、风险、建议、反对意见和触发重新评估的条件。', '分析', '["decision","facts"]'::jsonb, true, 530, CURRENT_TIMESTAMP),
  ('prompt-risk-review', '风险评估', '识别业务、技术、合规和执行风险。', E'评估以下计划的风险：\n{{plan}}\n\n按发生概率和影响程度排序，覆盖业务、技术、数据、安全、合规和执行风险，并给出预防措施、监控指标和应急预案。', '分析', '["plan"]'::jsonb, true, 540, CURRENT_TIMESTAMP),
  ('prompt-product-hero-image', '商品主视觉', '生成突出商品本体和卖点的商业主视觉。', '生成{{product}}的商业主视觉，画面比例{{ratio}}，视觉风格{{style}}。商品外观、包装文字和结构必须准确，主体清晰完整，光线自然，背景服务于卖点，预留标题区域，不添加虚构认证或参数。', '图片', '["product","style","ratio"]'::jsonb, true, 610, CURRENT_TIMESTAMP),
  ('prompt-editorial-portrait', '杂志人像', '生成自然、有叙事感的编辑类人像。', '创作一张{{subject}}的杂志编辑人像，场景为{{setting}}，情绪{{mood}}。保持自然肤质和真实比例，使用有方向性的柔和光线、克制的色彩和清晰的环境叙事，避免过度磨皮。', '图片', '["subject","setting","mood"]'::jsonb, true, 620, CURRENT_TIMESTAMP),
  ('prompt-campaign-poster', '活动海报', '生成层级清楚并预留文案区域的活动海报。', '为“{{theme}}”设计面向{{audience}}的活动海报，比例{{ratio}}。建立明确视觉焦点和信息层级，预留主标题、副标题、日期和行动按钮区域，保证移动端缩略图下仍清楚可读。', '图片', '["theme","audience","ratio"]'::jsonb, true, 630, CURRENT_TIMESTAMP),
  ('prompt-image-edit', '图片局部修改', '在保留原图一致性的前提下执行指定修改。', '编辑参考图片：{{change}}。必须保持{{preserve}}不变，并维持原图主体身份、透视、光线方向、材质、阴影和整体色彩一致。修改区域边缘自然，不改变未指定内容。', '图片', '["change","preserve"]'::jsonb, true, 640, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
