ALTER TABLE "User"
  ADD COLUMN "company" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "phone" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "adminNote" TEXT NOT NULL DEFAULT '';
