ALTER TABLE "SystemSetting" ADD COLUMN IF NOT EXISTS "sub2apiClientId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SystemSetting" ADD COLUMN IF NOT EXISTS "encryptedSub2apiClientSecret" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SystemSetting" ADD COLUMN IF NOT EXISTS "sub2apiClientSecretHint" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SystemSetting" ADD COLUMN IF NOT EXISTS "sub2apiRedirectUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SystemSetting" ADD COLUMN IF NOT EXISTS "sub2apiScopes" TEXT NOT NULL DEFAULT 'openid profile email';
ALTER TABLE "SystemSetting" ADD COLUMN IF NOT EXISTS "sub2apiAuthorizeUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SystemSetting" ADD COLUMN IF NOT EXISTS "sub2apiTokenUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SystemSetting" ADD COLUMN IF NOT EXISTS "sub2apiUserInfoUrl" TEXT NOT NULL DEFAULT '';
